matrix:
  include:
    - language: generic
      os: linux
      services:
        - docker
    - language: cpp
      os: osx
      osx_image: xcode6.4
      compiler: clang
cache:
  directories:
    - build/downloads
env:
  global:
    - secure: "KTCE8u2fxZ1xdxmW+K1ZyVuVpiVHVCi8a5iekDyUuTs8+r7qUtER33MESmfubseZyMxUQ460/ACAryDYkm4EJrtIKEmvYnNYjDv9vMba7G5T2u64wys+IOb5nvqxBXQynFjn7Xtfg3+DUMymfClxYBiO6aPI4iWpctHfkpiwM6VxKqtQopIcZMljpLH03kv24Bvw7Ev+iwlh0TH48ckc9XoW1LwQpHDB+OPntiV/0XxWYmuraRY5UFZpRBQmgmTrJa+j65j7AsJw0wLwIdUrRWiyJEYIsvI6jDjgBjIjkT04sav61febuta9PILKEYaDPL0g7jPM71c1H1oigjyj4GTXGO1O6v1rYDOiqlYarcNBNsnYcg3Oi7NeDISSL2aOt9GzlnrVK3WA5LwzMpeMIKP4EMjYwLLlf0ElPTQaoR954GeMzymBZ6SB1OlhJNsUEg7vv/RO8UZz0y/URD4ObZNl78dBJPLy4nJnWoUvpdvwZyHTpR9wbtyrnsVp+vYRA8pPtJWwafPOtZNGobtqXJbSgKgtwr5+P+mWfkSYs3uCfDCMyM02LYqkr/UdoxVKZg6ZIj7EwBh2WWzwIXgXkygven2l0u3xqDDb+0CSlsKpgKcQDlCOiEQFJFR7tctQWXak328iXfkXBMPRx00YKywtmEPSN3Go537U7r5I8ik="
    - secure: "x2E22efQWMxwNojAyx43U5G0FtWSpnqPKrvaSm3WCOIDQew7DLt0+dDj+NT3hqr0bgiDfKOTrNBcrPkvXF87rUdOoc7t/hN517X6SAeGCaczxcRqhiaPqnQYDV5tbd03I+G1GTfLklAZuxt6+rHUIIgFohQ3GL2MSBlELvJWIopWWNFbfENGe7o2ojeE0Vazewv62lRGixADbNHxDIe6Bh6lN7abfIYLrUs9OvT8Y9d6TRj4jsS5kqIZrKs6VSWrDBOTseEr1GH4Q1nziMVaSLvIM3FvOwm2pAv19aw6ZkL0mN1jZFh4Z6sMcRer4KAnA9egwcFFvbuHHDBdAljJeAf+MEh+PvFIkDZhujBmxfGxCID6HeUWyj1y5hDdkxhkTg803iMu5m6QLm1ofiFs21hDfZu+yxufszjKMwtg00NqPaGYbOx7Bpi5/XWOWVgDURUQKieHUZxO4zht2cs+uV1AIToHOQh+P7y6dOwOnXSonBei1V4iCksy4V29Tf7HBgTbgU+Dwcgd195MMqxZiyXPklMRcW+LudLHRWfqy7gNN28bvt1OiCMrXPvvwmZIWfj+FpO0JGU2MAe4I6UJEsQp4TlkZ5q5K+LpZphCz5A2sWMX53/MExNaeLyTTa0tcDGKflaMKBgCdMtkwXJVph7qknPF+hqRvLid92OOJ5A="
before_script:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      # Use a more verbose travis_wait implementation
      . .travis_wait
      # Delete the outdated `/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA` certificate
      sudo security delete-certificate -Z 2F173F7DE99667AFA57AF80AA2D1B12FAC830338 /System/Library/Keychains/SystemRootCertificates.keychain
      rvm osx-ssl-certs update $(travis_internal_ruby)
      mkdir -p build
      cd build
    fi
script:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      cmake -G "Xcode" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk ..
      travis_wait 70 cmake --build . --config RelWithDebInfo
    fi
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export SHORT_COMMIT=${TRAVIS_COMMIT::8}
      export DOCKER_REPO=freeorion/freeorion-travis-build
      # get latest remote tag
      export DOCKER_RTAG=$(curl -s https://registry.hub.docker.com/v2/repositories/${DOCKER_REPO}/tags/ | jq '.results[]["name"]' | sort -rn | sed -n '2s/"//gp')
      # calculate next tag
      export DOCKER_NTAG=$((${DOCKER_RTAG} + 1))
      docker pull ${DOCKER_REPO}:${DOCKER_RTAG}
      docker build -f Dockerfile -t ${DOCKER_REPO}:${SHORT_COMMIT} .
      # calculate current tag
      export DOCKER_CTAG=$(docker inspect ${DOCKER_REPO}:${SHORT_COMMIT} | jq '.[]["ContainerConfig"]["Labels"]["version"]?' | sed -n '2s/"//gp')
      if [[ "${DOCKER_CTAG}" != "${DOCKER_RTAG}" ]]; then
        docker tag ${DOCKER_REPO}:${SHORT_COMMIT} ${DOCKER_REPO}:${DOCKER_NTAG}
        docker tag ${DOCKER_REPO}:${SHORT_COMMIT} ${DOCKER_REPO}:latest
      fi
    fi
after_success:
  - >
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
      docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}"
      docker push ${DOCKER_REPO}:${DOCKER_NTAG}
      docker push ${DOCKER_REPO}:latest
    fi
deploy:
  provider: releases
  api-key:
    secure: "fRPiVwWwyhGlR+F+Vzt9ZDszc+TXrkq+UZ8uYRT//H0NrYV+OvvkAhE4GxRqDC2SfTnwJ5wCc07yf2Prxv7Zm5KYAJcCjBA04L9D/MD03+McGJIiKpg86XEOwAAUGuCB74gyCj3tuIKkQsops8HzYyNsP10q0o0kXQj0OmZSXFKAs1e6YsbkRM+FaPtwcA9Fek4EIp8+Wcq1HeMdR+uCDzguYjjHGBBkO4IMljqdtYLsj7PVQKiI8tmlnHbrBkEXAVqLjKRxzfiYFfKk7XA8N5TN8oOGnw9o77ic/bdeUoJmzgcCP/dfB+1UDCXKXMcA1vU89kzf7XDiHAZgNO0nJmSVCl3fSZKQA/F1/B90LEGVDofnpOJMLCpLFN8WHAGS5o4xldIafMgDSLW8rhLHOJhXPjUORQ1oiZDrTxQ+3FKdlNvPKzZsaac7r454z8g2/9ourhqV1PIJdS1hrM/g6ByTOxrPhn1+e6Yv0vENEDhRZ/ZGmjn+TQTSuyyuu0nKG9ky1jC7/aoAWNQuN7jRXrFOH8HAUhArTdNPTYEHBqprAdHh5ccLUpv4yRvCNqxmmTu+c/95vVDQ3s2RndGqwp9xSNh+7nSBfrW+78f7fY4X0X/7wBQ/1sp7GbxWuWVkvkgDC5pvaUKuiddoQoYJysXUOADMBh6FBO/zZh76HSE="
  # Undocumented flag to create a draft release
  draft: true
  file_glob: true
  file: FreeOrionSDK_*.dmg
  skip_cleanup: true
  on:
    tags: true
