version: ci-{build}
branches:
  only:
    - master
init:
  - git config --global core.eol native
  - git config --global core.autocrlf true
install:
  - '"C:\Program Files (X86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"'
build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12" ..
  - cmake --build . --config RelWithDebInfo
