image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

version: ci-{build}

environment:
  matrix:
   - TOOlSET: v140_xp
     GENERATOR: "Visual Studio 14 2015"
     PLATFORM: Win32
   - TOOlSET: v141_xp
     GENERATOR: "Visual Studio 15 2017"
     PLATFORM: Win32
   - TOOlSET: v141
     GENERATOR: "Visual Studio 15 2017"
     PLATFORM: x64
   - TOOlSET: v142
     GENERATOR: "Visual Studio 16 2019"
     PLATFORM: Win32
   - TOOlSET: v142
     GENERATOR: "Visual Studio 16 2019"
     PLATFORM: x64
cache:
  - build\downloads -> Sources.cmake
init:
  - git config --global core.eol native
  - git config --global core.autocrlf true
before_build:
  - if not exist build\NUL mkdir build
  - cd build
build_script:
  - cmake -G "%GENERATOR%" -T %TOOLSET% -A %PLATFORM% ..
  - cmake --build . --config RelWithDebInfo -- /maxcpucount /property:BuildInParallel=true /property:CL_MPCount=2 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
test: off
artifacts:
  - name: FreeOrionSDK_Package
    path: build\FreeOrionSDK_*.zip
deploy:
  provider: GitHub
  auth_token:
    secure: mqkOnTRfVVRNofBa9tTEb2jdIjmJNhH7G8DPc05rxIy6/hkOl9y/h9FzB2MJD4rS
  description: 'Release of the FreeOrionSDK'
  artifact: FreeOrionSDK_Package
  draft: true
  force_update: true
  on:
    appveyor_repo_tag: true

matrix:
  exclude:
    - image: Visual Studio 2015
      GENERATOR: "Visual Studio 15 2017"
    - image: Visual Studio 2015
      GENERATOR: "Visual Studio 16 2019"
    - image: Visual Studio 2017
      GENERATOR: "Visual Studio 14 2015"
    - image: Visual Studio 2017
      GENERATOR: "Visual Studio 16 2019"
    - image: Visual Studio 2019
      GENERATOR: "Visual Studio 14 2015"
    - image: Visual Studio 2019
      GENERATOR: "Visual Studio 15 2017"
  allow_failures:
    - image: Visual Studio 2019
